spring.application.name=console-bank-app
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.auto-index-creation=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized
management.health.mongodb.enabled=false
app.admin.username=${APP_ADMIN_USERNAME:admin}
app.admin.password=${APP_ADMIN_PASSWORD:}
app.jwt.secret=${APP_JWT_SECRET:}
app.jwt.issuer=${APP_JWT_ISSUER:}
app.jwt.ttl=${APP_JWT_TTL:}
